version: '3'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql

  shs:
    build: .
    container_name: shs
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./persist:/persist
